### ISSUE TITLE
slackbuilds.org already included this slackbuild.

### ISSUE THREAD

**Issue by nnnewb** [slackwarecn/extra-cmake-modules#1]
[slackbuild](https://slackbuilds.org/repository/14.2/development/extra-cmake-modules)
This repository is no longer needed.

**Comment by Arondight** [comment]
https://slackbuilds.org/repository/14.2/development/extra-cmake-modules

这个项目扔这儿吧，我把https://github.com/slackwarecn/repo 更一下

**Comment by Arondight** [comment]
https://github.com/slackwarecn/repo/blob/master/Changes
